version: '3.8'
services:
  notice-app:
    build: .
    ports:
      - "${NOTICE_SERVER_PORT}:${NOTICE_SERVER_PORT}"
    depends_on:
      - notice-db
    environment:
      - SERVER_PORT=${NOTICE_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notice-db:5432/${NOTICE_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${NOTICE_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${NOTICE_DB_PASS}

  notice-db:
    image: postgres:15
    ports:
      - "${NOTICE_DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${NOTICE_DB_NAME}
      - POSTGRES_USER=${NOTICE_DB_USER}
      - POSTGRES_PASSWORD=${NOTICE_DB_PASS}
    volumes:
      - notice_postgres_data:/var/lib/postgresql/data

volumes:
  notice_postgres_data:
